### ISSUE TITLE
Code quality (possible errors found by cppcheck)

### ISSUE THREAD

**Issue by jplatte** [therocode/featherkit#59]
This is what cppcheck found when ran with `--enable=performance,portability,style,warning --inconclusive --std=c++11` on the incoming branch, excluding errors from generated C source files:

    [src/audio/audiofilestream.cpp:11]: (style) Variable 'desiredSampleAmount' is assigned a value that is never used.
    [src/audio/audioplayer.cpp:185]: (style, inconclusive) Consecutive return, break, continue, goto or throw statements are unnecessary.
    [src/rendering/textsurface.cpp:15]: (style) Variable 'error' is assigned a value that is never used.
    [src/rendering/textsurface.cpp:318]: (style) Variable 'currentWordStart' is assigned a value that is never used.
    [src/ui/inputhandler.cpp:99]: (performance) Possible inefficient checking for 'newEvents' emptiness.

**Comment by therocode** [comment]
Thanks, and fixed all of them!
